apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-tls
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - secretName: tls-postfix
      hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"