name: build and deploy container

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  service:
    uses: kubernetes-mail-server/.github/.github/workflows/service.yml@main
    secrets: inherit
    with:
      name: postfix
      helm-args: >-
        --set hostname=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.HOSTNAME}")
        --set haproxy_smtpd=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.POSTFIX_PORT}")
        --set plain_smtpd=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.POSTFIX_SUBMISSION_PORT}")
